#!/bin/bash

# Constants --------------------------------------------------------------------------
readonly SSH_CONFIG='/etc/ssh/sshd_config'
readonly SSH_DAEMON='/usr/sbin/sshd'

${SSH_DAEMON} -D -e -f ${SSH_CONFIG}

