#!/bin/bash

# This script will copy the passed paramter to all remove nodes
# CALL mpicopy [Path to hostfile] [Path to File or Dir] [Remote path]

printHelp() {
	echo -e 'Program for copying mpi programs to other nodes.\n'
	echo USAGE:
	echo -e '\tmpicopy [OPTIONS] [HOSTSFILE] [directory or file]\n'
	echo Hostsfile:
	echo -e '\tA file with node names of IP addresses of the nodes\n'
	echo Options:
	echo -e '\t -h\t --help\t\t\t Print this message'
	echo -e '\t -rp\t --remotePath\t[PATH]\t Remote path to copy to'
	echo -e '\n'
}

# Parameters ----------------------------------------------------------------------------
HELP=0
HOSTS_FILE=""
DATA=""
REMOTE_PATH=$(pwd)

while [[ "$#" -gt 0 ]]; do case $1 in
  -h|--help) HELP=1;;
  -rp|--remotePath) REMOTE_PATH=$2; shift;;
  *) HOSTS_FILE=$1; DATA=$2; shift;;
esac; shift; done

if [ $HELP -eq 1 ]; then
	printHelp
	exit 0
fi
if [ "$HOSTS_FILE" = "" ]; then 
	printHelp
	exit 1
fi
if [ ! -f $HOSTS_FILE ]; then
	echo $HOSTS_FILE does not exit!!!
	exit 1
fi
if  [ ! -f $DATA ] && [ ! -d $DATA ]; then
	echo $DATA does not exists!!!
	exit 2
fi

# Helper funcions -----------------------------------------------------------------------
fHCutLine() {
	if [ $# -lt 2 ]; then exit 1; fi
	echo $1 | tr '\t' ' ' | tr -s ' ' | cut -d' ' -f$2
}

# Main ----------------------------------------------------------------------------------
user=$(whoami)

while IFS= read -r line; do
	tnname=$(fHCutLine "${line}" 2)
	if [ ${tnname} = ${HOSTNAME} ]; then continue; fi
	echo "Sending to ${user}@${tnname}"
	scp -r ${DATA} ${user}@${tnname}:${REMOTE_PATH} &
done < ${HOSTS_FILE}

wait
echo 'Sending done!!!'
