#!/bin/bash

# This script will copy the passed paramter to all remove nodes
# CALL mpirunsh [hostsfile] [Shell command]

printHelp() {
	echo -e 'Program for copying mpi programs to other nodes.\n'
	echo USAGE:
	echo -e '\tmpirunsh [OPTIONS] [HOSTSFILE] [Shell command]\n'
	echo Hostsfile:
	echo -e '\tA file with node names of IP addresses of the nodes\n'
	echo Options:
	echo -e '\t -h\t --helpt\t\t\t Print this message'
	echo -e '\n'
}

# Parameters ----------------------------------------------------------------------------
HELP=0
HOSTS_FILE=""
REMOTE_COMMAND=""

while [[ $# -gt 0 ]]; do case $1 in
  -h|--help) HELP=1;;
  *) HOSTS_FILE=$1; REMOTE_COMMAND=$2; shift;;
esac; shift; done

if [ ${HELP} -eq 1 ]; then 
	printHelp
	exit 0
fi
if [ "${HOSTS_FILE}" = "" ] || [ "${REMOTE_COMMAND}" = "" ]; then 
	printHelp
	exit 1
fi
if [ ! -f ${HOSTS_FILE} ]; then
	echo ${HOSTS_FILE} does not exit!!!
	exit 1
fi

# Helper funcions -----------------------------------------------------------------------
fHCutLine() {
	if [ $# -lt 2 ]; then exit 1; fi
	echo $1 | tr '\t' ' ' | tr -s ' ' | cut -d' ' -f$2
}

# Main ----------------------------------------------------------------------------------
user=$(whoami)

while IFS= read -r line; do
	tnname=$(fHCutLine "${line}" 2)
	if [ ${tnname} = ${HOSTNAME} ]; then continue; fi
	echo "Runing on ${tnname}"
	ssh ${user}@${tnname} ${REMOTE_COMMAND} &
done < ${HOSTS_FILE}

wait
echo Sending done!!!
