#!/bin/sh

# This script will copy the passed paramter to all remove nodes
# CALL mpicopy [Path to File or Dir] [Command for build project] [Remote path]

# Parameters ----------------------------------------------------------------------------
if [ $# -lt 2 ]; then 
	echo Need 2 arguments
	exit 1
fi

HOSTS_FILE=$1
REMOTE_COMMAND=$2

# Helper funcions -----------------------------------------------------------------------
fHCutLine() {
	if [ $# -lt 2 ]; then exit 1; fi
	echo $1 | tr '\t' ' ' | tr -s ' ' | cut -d' ' -f$2
}

# Main ----------------------------------------------------------------------------------
user=$(whoami)

while IFS= read -r line; do
	tnname=$(fHCutLine "${line}" 2)
	if [ ${tnname} = ${HOSTNAME} ]; then continue; fi
	echo "Runing on ${tnname}"
	ssh ${user}@${tnname} ${REMOTE_COMMAND}
done < ${HOSTS_FILE}

